2025-04-01 21:37:45,707 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-01 21:37:47,679 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-01 21:39:10,793 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-01 21:39:13,026 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-01 21:56:26,797 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-01 21:56:28,985 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-01 21:56:35,863 INFO: Tentando atualizar assunto 1 para ordem 0 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:56:35,866 WARNING: Assunto 1 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:56:35,879 INFO: Tentando atualizar assunto 7 para ordem 1 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:56:35,881 WARNING: Assunto 7 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:56:35,886 INFO: Tentando atualizar assunto 4 para ordem 2 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:56:35,888 WARNING: Assunto 4 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:57:37,553 INFO: Tentando atualizar assunto 1 para ordem 0 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:57:37,554 WARNING: Assunto 1 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:57:37,556 INFO: Tentando atualizar assunto 7 para ordem 1 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:57:37,557 WARNING: Assunto 7 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:57:37,558 INFO: Tentando atualizar assunto 4 para ordem 2 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:57:37,561 WARNING: Assunto 4 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:57:49,930 INFO: Tentando atualizar assunto 1 para ordem 0 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:57:49,933 WARNING: Assunto 1 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:57:49,937 INFO: Tentando atualizar assunto 4 para ordem 1 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:57:49,938 WARNING: Assunto 4 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:57:49,942 INFO: Tentando atualizar assunto 7 para ordem 2 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:57:49,944 WARNING: Assunto 7 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:58:08,554 INFO: Tentando atualizar assunto 1 para ordem 0 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:58:08,556 WARNING: Assunto 1 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:58:08,561 INFO: Tentando atualizar assunto 4 para ordem 1 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:58:08,563 WARNING: Assunto 4 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-01 21:58:08,568 INFO: Tentando atualizar assunto 7 para ordem 2 [in C:\Python\AdGest\app\routes.py:547]
2025-04-01 21:58:08,569 WARNING: Assunto 7 não encontrado ou não pertence ao usuário 2 [in C:\Python\AdGest\app\routes.py:552]
2025-04-02 14:35:32,525 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 14:35:34,905 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 14:45:13,238 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 14:45:15,660 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 14:59:49,977 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 15:00:02,242 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 15:00:09,801 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 15:00:12,026 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 15:13:48,624 INFO: Tentando atualizar assunto 6 para ordem 0 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:48,627 INFO: Assunto 6 atualizado com nova ordem 0 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:48,641 INFO: Tentando atualizar assunto 8 para ordem 1 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:48,645 INFO: Assunto 8 atualizado com nova ordem 1 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:48,657 INFO: Tentando atualizar assunto 3 para ordem 2 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:48,660 INFO: Assunto 3 atualizado com nova ordem 2 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:48,679 INFO: Tentando atualizar assunto 1 para ordem 3 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:48,681 INFO: Assunto 1 atualizado com nova ordem 3 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:48,684 INFO: Tentando atualizar assunto 5 para ordem 4 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:48,685 INFO: Assunto 5 atualizado com nova ordem 4 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:48,690 INFO: Tentando atualizar assunto 4 para ordem 5 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:48,692 INFO: Assunto 4 atualizado com nova ordem 5 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:57,485 INFO: Tentando atualizar assunto 6 para ordem 0 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:57,487 INFO: Assunto 6 atualizado com nova ordem 0 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:57,499 INFO: Tentando atualizar assunto 8 para ordem 1 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:57,501 INFO: Assunto 8 atualizado com nova ordem 1 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:57,518 INFO: Tentando atualizar assunto 3 para ordem 2 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:57,520 INFO: Assunto 3 atualizado com nova ordem 2 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:57,530 INFO: Tentando atualizar assunto 1 para ordem 3 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:57,533 INFO: Assunto 1 atualizado com nova ordem 3 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:57,544 INFO: Tentando atualizar assunto 5 para ordem 4 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:57,545 INFO: Assunto 5 atualizado com nova ordem 4 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:57,548 INFO: Tentando atualizar assunto 4 para ordem 5 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:57,549 INFO: Assunto 4 atualizado com nova ordem 5 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:58,635 INFO: Tentando atualizar assunto 6 para ordem 0 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:58,638 INFO: Assunto 6 atualizado com nova ordem 0 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:58,643 INFO: Tentando atualizar assunto 8 para ordem 1 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:58,644 INFO: Assunto 8 atualizado com nova ordem 1 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:58,658 INFO: Tentando atualizar assunto 3 para ordem 2 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:58,660 INFO: Assunto 3 atualizado com nova ordem 2 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:58,676 INFO: Tentando atualizar assunto 5 para ordem 3 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:58,677 INFO: Assunto 5 atualizado com nova ordem 3 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:58,689 INFO: Tentando atualizar assunto 4 para ordem 4 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:58,690 INFO: Assunto 4 atualizado com nova ordem 4 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:13:58,695 INFO: Tentando atualizar assunto 1 para ordem 5 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:13:58,696 INFO: Assunto 1 atualizado com nova ordem 5 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:14:01,432 INFO: Tentando atualizar assunto 6 para ordem 0 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:14:01,434 INFO: Assunto 6 atualizado com nova ordem 0 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:14:01,442 INFO: Tentando atualizar assunto 8 para ordem 1 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:14:01,445 INFO: Assunto 8 atualizado com nova ordem 1 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:14:01,452 INFO: Tentando atualizar assunto 4 para ordem 2 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:14:01,454 INFO: Assunto 4 atualizado com nova ordem 2 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:14:01,485 INFO: Tentando atualizar assunto 3 para ordem 3 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:14:01,488 INFO: Assunto 3 atualizado com nova ordem 3 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:14:01,495 INFO: Tentando atualizar assunto 5 para ordem 4 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:14:01,496 INFO: Assunto 5 atualizado com nova ordem 4 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:14:01,501 INFO: Tentando atualizar assunto 1 para ordem 5 [in C:\Python\AdGest\app\routes.py:547]
2025-04-02 15:14:01,502 INFO: Assunto 1 atualizado com nova ordem 5 [in C:\Python\AdGest\app\routes.py:550]
2025-04-02 15:37:17,673 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 15:37:19,934 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 15:41:00,933 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 15:41:03,080 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 16:07:57,423 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 16:08:08,310 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
2025-04-02 16:12:20,003 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:42]
